

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]



jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "Hello World"

  
