

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    if: "! $(git diff --quiet HEAD^ HEAD --name-only | grep -v '^helm-chart/')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Hello World : Build"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    if: "$(git diff --quiet HEAD^ HEAD --name-only | grep -q '^helm-chart/')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Hello World : Deploy"
