

name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]



jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: production
    # if: ${{ !contains(join(github.event.commits.*.modified, ' '), 'helm-chart/') }}
    if: ${{ !contains(github.event.head_commit.message, 'helm-chart') && !contains(join(github.event.commits.*.added, ' '), 'helm-chart') && !contains(join(github.event.commits.*.modified, ' '), 'helm-chart') && !contains(join(github.event.commits.*.removed, ' '), 'helm-chart') }}
   

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "Hello World : Build"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "Hello World : Deploy"

  
